[phases.setup]
nixPkgs = ["nodejs-18_x", "npm", "postgresql"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "npm run db:generate",
  "npm run db:migrate",
  "npm run seed"
]

[start]
cmd = "npm run start:prod"