[phase.setup]
nixPkgs = ["nodejs"]

[phase.install]
cmds = ["npm install"]

[phase.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"

[variables]
NODE_ENV = "production"
NODE_VERSION = "20"